AllCops:
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude: ["spec/**/*.rb"]

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 100
  Exclude: ["spec/**/*.rb"]

Metrics/MethodLength:
  Max: 20

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Lint/RedundantSplatExpansion:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
